#include <assert.h>
#include <ctype.h>
#include <fcntl.h>
#include <glib.h>
#include <ncurses.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
