
CFLAGS = -ansi $(WARN_FLAGS)
#WARN_FLAGS = -pedantic -Wall -Wextra -Werror
#WARN_FLAGS += -Wno-error=unused-but-set-variable
#WARN_FLAGS += -Wno-error=unused-parameter
#WARN_FLAGS += -Wno-error=format

all: makeheaders
clean:
	-rm -f makeheaders

